package com.example.alexnelson.compositionapplication;

/**
 * Created by Alex Nelson on 19/03/2017.
 */

public class CommentOnly {

    // TODO Class for to do list and other relevant documentation
    //USE SURFACEVIEW AND OPENGL
    // NEED TO FIND WAY OF TRANFERRIGN BITMAP HEIGHT AND WIDTH INFO TO SETUPTRIANGE METHOD IN RENDERER

    //IMPLEMENT android:configChanges="orientation|keyboardHidden|screenSize" WITH onConfigChanged() METHOD IMPLEMENTATION INSTEAD OF
    //RESTARTING ACTIVTY FOR SPEED
    //ADJUST SCREEN DIMENSIONS IN RENDERER TO ACTUAL LAYOUT
    //USE GL IMPLEMENTATION FO EVENT HANDLERS
    //MAYBE HAVE A METHOD FOR EACH CASE IN RENDERER processTouchEvent() METHOD
    //MAKE touchState CONSTANTS CONSTANTS IN ENUMERATION
    //USE OMIT BREAK IN SWITCH STATEMENT????
    //USE APPROPRIATELY DELEGATED METHODS FOR RENDERER EVENT PROCESSING //ALSO PUT EVENT IDS INTO TRY CLAUSES TO SHORE UP INTEGRITY
    //MULTIPLIER FOR IMAGE HEIGHT AND WIDTH SHOULD USE THE VALUES CALCULATED FOR THE IMAGE VERTICES IN drawImage()
    //Y VERTICES VALUES NEED TO BE SORTED OUT
    //NEED TO FILTER ANY INPUT OUTSIDE THE BOUNDS OF THE PICTURE FROM
    //MAYBE USE ANDROID NATIVE ZOOM FUNCTIONALITY??
    //USE DIFFERENT THREAD FOR MAGNIFICATION
    //fm in front of variables stands for function member
    //MAKE SCALE ZOOM ON CENTRE OF IMAGE AND THEN PAN
    //DELEGATE GESTURE AND INPUT HANDLING TO UI THREAD
    //USE MULTI-THREADED RENDERER
    //Constantly creating shaders is very costly



}

//Initially implemented zoom by changing texture uv cooridinates, but then realised that it caused program to crash